#!/usr/bin/env bash
# This script adds an X-Served-By header to the Nginx configuration file
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R "$USER:$USER" /etc/nginx
server_name=$(hostname)
sudo sed -i "/http {/a \        add_header X-Served-By \"$server_name\";" /etc/nginx/nginx.conf
sudo service nginx restart
