#!/usr/bin/env bash
# This script install and configure HAproxy on your Ib-01 server.

apt-get -y update
apt-get -y install haproxy
echo "
frontend beingjay-frontend
	bind *:80
	mode http
	default_backend beingjay-backend

backend beingjay-backend
	balance roundrobin
	server 147941-web-01 18.204.8.143:80 check
	server 147941-web-02 34.232.72.63:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
