#!/usr/bin/env bash
# Configure nginx and must say nginx is not running
sudo sed -i 's/8080 default_server/80 default_server/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo rm /var/run/nginx.pid
